"""Initial migration: all tables

Revision ID: 18c437401cb4
Revises: 
Create Date: 2025-11-15 09:15:41.606143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c437401cb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('hostname', sa.Text(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_default_password', sa.Boolean(), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True),
    sa.Column('are_notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('public_key_gpg', sa.Text(), nullable=True),
    sa.Column('public_key_ssh', sa.Text(), nullable=True),
    sa.Column('private_key_ssh', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('backup_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('schedule', sa.Text(), nullable=False),
    sa.Column('retention', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('last_status', sa.Enum('sukces', 'błąd', name='backup_status'), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backup_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['backup_tasks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('informacja', 'błąd', 'logowanie', name='event_type'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['backup_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('backup_files')
    op.drop_table('backup_tasks')
    op.drop_table('settings')
    op.drop_table('servers')
    # ### end Alembic commands ###
