"""Add status to Server

Revision ID: b18c88333824
Revises: 18c437401cb4
Create Date: 2025-11-15 18:10:12.546258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18c88333824'
down_revision = '18c437401cb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('aktywny', 'nieaktywny', name='status_enum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
