"""different key pairs for commands and rsync

Revision ID: dd44fdf3450d
Revises: b18c88333824
Create Date: 2025-11-20 08:14:38.417058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd44fdf3450d'
down_revision = 'b18c88333824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('command_public_key_ssh', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('command_private_key_ssh', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rsync_public_key_ssh', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rsync_private_key_ssh', sa.Text(), nullable=True))
        batch_op.drop_column('public_key_ssh')
        batch_op.drop_column('private_key_ssh')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private_key_ssh', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('public_key_ssh', sa.TEXT(), nullable=True))
        batch_op.drop_column('rsync_private_key_ssh')
        batch_op.drop_column('rsync_public_key_ssh')
        batch_op.drop_column('command_private_key_ssh')
        batch_op.drop_column('command_public_key_ssh')

    # ### end Alembic commands ###
